// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZPcSi9Y7_Ik4dZPsYFDn9ZC5XWTD6ts8',
    appId: '1:536002207587:web:0cfc6a55110da4e029bd56',
    messagingSenderId: '536002207587',
    projectId: 'braintoss-dev',
    authDomain: 'braintoss-dev.firebaseapp.com',
    storageBucket: 'braintoss-dev.appspot.com',
    measurementId: 'G-L2MW1PDJ1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjGCYndGMjfjDTH8TyeSmmoknJJHuTr2A',
    appId: '1:536002207587:android:8f85af4b2135819629bd56',
    messagingSenderId: '536002207587',
    projectId: 'braintoss-dev',
    storageBucket: 'braintoss-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1gSz74Q-BYEYCiJcShd3jAZ-kYrft684',
    appId: '1:536002207587:ios:a6e47be31aac51d329bd56',
    messagingSenderId: '536002207587',
    projectId: 'braintoss-dev',
    storageBucket: 'braintoss-dev.appspot.com',
    iosClientId: '536002207587-ifb9ccfpkd1uddcgcvokc88csmddd4s7.apps.googleusercontent.com',
    iosBundleId: 'com.braintoss.braintoss',
  );
}
